"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Activity, ArrowLeft, BarChart3, Bell, CalendarDays, Check,
  ChevronRight, Clock3, FileText, Filter, History, Home, Moon,
  Pencil, Pill, Plus, RotateCw, Scale, Sun, Syringe, Trash2, UserRound, X, Zap
} from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { doseOptions, doseOptionKey, doseOptionLabel } from "@/lib/medication-options";
import { syncDoseReminders } from "@/lib/native-notifications";

type Screen="today"|"history"|"progress"|"plan";
type Dose={id:number;medication:string;ingredient:string;dose:string;amount:string;date:string;time:string;site:string;note:string;createdAt:string;periodId:number};
type Daily={id:number;date:string;appetite:number;energy:number;symptoms:string[];weight?:number;createdAt:string};
type Period={id:number;medication:string;ingredient:string;dose:string;amount:string;start:string;end?:string;interval:string;day:string;time:string;active:boolean};
type Profile={name:string;gender?:string;birthDate?:string;reminders:boolean;reminderTime:string;onboarded:boolean};
type Store={profile:Profile;doses:Dose[];dailies:Daily[];periods:Period[];dark:boolean};

const greetingFor=(name:string)=>{const h=new Date().getHours();const part=h<6?"İyi geceler":h<12?"Günaydın":h<18?"İyi günler":"İyi akşamlar";return `${part}, ${name}`};
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const timeKey=()=>new Date().toTimeString().slice(0,5);
const dailyAverage=(entries:Daily[],key:"appetite"|"energy",date=dateKey())=>{const values=entries.filter(d=>d.date===date&&Number.isFinite(d[key]));return values.length?(values.reduce((sum,d)=>sum+d[key],0)/values.length).toLocaleString("tr-TR",{maximumFractionDigits:1}):"—"};
const addDays=(iso:string,n:number)=>{const d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+n);return dateKey(d)};
const elapsed=(start:string,end=dateKey())=>Math.max(0,Math.round((new Date(end+"T12:00:00").getTime()-new Date(start+"T12:00:00").getTime())/86400000));
const sortedDoses=(d:Dose[])=>[...d].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));
const nextDose=(p:Period,doses:Dose[])=>{if(p.interval==="Plansız kullanım")return null;const last=sortedDoses(doses.filter(d=>d.periodId===p.id))[0];const days=p.interval==="Her gün"?1:Number(p.interval.match(/\d+/)?.[0]||7);if(last)return addDays(last.date,days);if(p.start>=dateKey())return p.start;const elapsedDays=elapsed(p.start);return addDays(p.start,Math.ceil(elapsedDays/days)*days)};
const pretty=(iso:string)=>new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"long",year:"numeric"}).format(new Date(iso+"T12:00:00"));
const fullPretty=(iso:string)=>new Intl.DateTimeFormat("tr-TR",{weekday:"long",day:"numeric",month:"long"}).format(new Date(iso+"T12:00:00"));
const stamp=()=>new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date());
const addedTime=(d:Daily)=>d.createdAt?.match(/\b([01]\d|2[0-3]):[0-5]\d\b/)?.[0];
const medicationOptions=[
  {name:"Ozempic",ingredient:"Semaglutid"},{name:"Mounjaro",ingredient:"Tirzepatid"},
  {name:"Wegovy",ingredient:"Semaglutid"},{name:"Rybelsus",ingredient:"Semaglutid"},{name:"Saxenda",ingredient:"Liraglutid"}
];
const defaultStore:Store={
  profile:{name:"",reminders:false,reminderTime:"09:00",onboarded:false},dark:true,
  periods:[{id:1,medication:"Mounjaro",ingredient:"Tirzepatid",dose:"",amount:"",start:dateKey(),interval:"Her 7 günde bir",day:"",time:"20:00",active:true}],
  doses:[],
  dailies:[]
};

export default function Page(){
  const [data,setData]=useState<Store>(defaultStore),[ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>("today"),[previewOnboarding,setPreviewOnboarding]=useState(false);
  const [doseOpen,setDoseOpen]=useState(false),[checkOpen,setCheckOpen]=useState(false),[periodOpen,setPeriodOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false);
  const [selectedDose,setSelectedDose]=useState<Dose|null>(null),[selectedDaily,setSelectedDaily]=useState<Daily|null>(null),[historyFilter,setHistoryFilter]=useState("Tümü"),[filterOpen,setFilterOpen]=useState(false),[periodFilter,setPeriodFilter]=useState("active");
  const [progressTarget,setProgressTarget]=useState<string|null>(null),[editDose,setEditDose]=useState<Dose|null>(null),[editDaily,setEditDaily]=useState<Daily|null>(null);
  const go=(s:Screen)=>{setProgressTarget(null);setScreen(s);window.scrollTo(0,0)};
  const goMetric=(id:string)=>{setPeriodFilter("active");setProgressTarget(id);setScreen("progress")};
  useEffect(()=>{if(screen!=="progress"||!progressTarget)return;const timer=setTimeout(()=>{const section=document.getElementById(progressTarget);section?.scrollIntoView({block:"start"});section?.focus({preventScroll:true})},100);return()=>clearTimeout(timer)},[screen,progressTarget]);
  // localStorage yalnızca tarayıcıda var, bu yüzden ilk okuma render sırasında değil
  // bağlanmadan sonra yapılmak zorunda. Kural burada geçerli değil.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setPreviewOnboarding(new URLSearchParams(window.location.search).get("onboarding")==="1");try{const raw=localStorage.getItem("dosekey-v2");if(raw){const parsed=JSON.parse(raw);if(parsed.profile&&Array.isArray(parsed.periods)&&parsed.periods.length&&Array.isArray(parsed.doses)&&Array.isArray(parsed.dailies))setData(parsed)}}catch{/* Preserve unreadable storage; do not crash the interface. */}setReady(true)},[]);
  useEffect(()=>{if(!ready||previewOnboarding)return;localStorage.setItem("dosekey-v2",JSON.stringify(data));document.documentElement.classList.toggle("dark",data.dark)},[data,ready,previewOnboarding]);
  const active=data.periods.find(p=>p.active)??data.periods[0];
  useEffect(()=>{if(!ready||!active)return;void syncDoseReminders({enabled:data.profile.reminders,date:nextDose(active,data.doses),time:data.profile.reminderTime,interval:active.interval,medication:active.medication,dose:doseOptionLabel(active)}).catch(()=>{})},[ready,active,data.profile.reminders,data.profile.reminderTime,data.doses]);
  const filteredDoses=useMemo(()=>data.doses.filter(d=>periodFilter==="all"||d.periodId===(periodFilter==="active"?active?.id:Number(periodFilter))),[data.doses,periodFilter,active?.id]);
  const setProfile=(next:Partial<Profile>)=>setData(d=>({...d,profile:{...d.profile,...next}}));
  const saveDose=(dose:Omit<Dose,"id"|"createdAt">)=>{setData(d=>({...d,doses:editDose?d.doses.map(x=>x.id===editDose.id?{...x,...dose}:x):[{...dose,id:Date.now(),createdAt:stamp()},...d.doses]}));setEditDose(null)};
  const saveDaily=(daily:Omit<Daily,"id"|"createdAt">)=>{setData(d=>({...d,dailies:editDaily?d.dailies.map(x=>x.id===editDaily.id?{...x,...daily}:x):[{...daily,id:Date.now(),createdAt:stamp()},...d.dailies]}));setEditDaily(null)};
  const savePeriod=(period:Omit<Period,"id">)=>setData(d=>({...d,periods:[{...period,id:Date.now()},...d.periods.map(p=>({...p,active:false,end:p.active?new Date(new Date(period.start).getTime()-86400000).toISOString().slice(0,10):p.end}))]}));
  useEffect(()=>{type C={registerTool:(t:Record<string,unknown>,o?:{signal?:AbortSignal})=>void|Promise<void>};const c=(document as Document&{modelContext?:C}).modelContext;if(!c?.registerTool)return;const a=new AbortController();void Promise.resolve(c.registerTool({name:"get_dosekey_summary",title:"DoseKey özetini getir",description:"Aktif plan ve kayıt özetini getirir.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({activePeriod:active.dose+" / "+active.amount,doseCount:data.doses.length,dailyCount:data.dailies.length})},{signal:a.signal})).catch(()=>{});return()=>a.abort()},[active,data.doses.length,data.dailies.length]);
  if(!ready)return null;
  if(!data.profile.onboarded||previewOnboarding)return <Onboarding data={data} setData={setData} preview={previewOnboarding} exitPreview={()=>{window.history.replaceState(null,"",window.location.pathname);setPreviewOnboarding(false)}}/>;
  return <main className="app-shell">
    <div className="phone-surface">
      {screen==="today"&&<Today data={data} active={active} openDose={()=>setDoseOpen(true)} openCheck={()=>setCheckOpen(true)} openSettings={()=>setSettingsOpen(true)} toggleTheme={()=>setData(d=>({...d,dark:!d.dark}))} go={go} goMetric={goMetric}/>}
      {screen==="history"&&<HistoryScreen data={data} filter={historyFilter} openFilter={()=>setFilterOpen(true)} select={setSelectedDose} selectDaily={setSelectedDaily} openDose={()=>setDoseOpen(true)}/>}
      {screen==="progress"&&<Progress data={data} active={active} filter={periodFilter} setFilter={setPeriodFilter} doses={filteredDoses} select={setSelectedDose}/>}
      {screen==="plan"&&<Plan data={data} active={active} add={()=>setPeriodOpen(true)} select={id=>{setPeriodFilter(String(id));go("progress")}} toggleReminder={()=>setData(d=>({...d,profile:{...d.profile,reminders:!d.profile.reminders}}))} setReminderTime={reminderTime=>setProfile({reminderTime})}/>}
      <BottomNav screen={screen} setScreen={go}/>
    </div>
    <DoseFlow open={doseOpen} close={()=>{setDoseOpen(false);setEditDose(null)}} active={active} periods={data.periods} editing={editDose} save={saveDose}/>
    <DailyFlow open={checkOpen} close={()=>{setCheckOpen(false);setEditDaily(null)}} editing={editDaily} save={saveDaily}/>
    <PeriodFlow open={periodOpen} close={()=>setPeriodOpen(false)} active={active} save={savePeriod}/>
    <DoseDetail dose={selectedDose} close={()=>setSelectedDose(null)} period={data.periods.find(p=>p.id===selectedDose?.periodId)} edit={()=>{setEditDose(selectedDose);setSelectedDose(null);setDoseOpen(true)}} remove={()=>{if(!selectedDose)return;setData(d=>({...d,doses:d.doses.filter(x=>x.id!==selectedDose.id)}));setSelectedDose(null)}}/>
    <DailyDetail daily={selectedDaily} close={()=>setSelectedDaily(null)} edit={()=>{setEditDaily(selectedDaily);setSelectedDaily(null);setCheckOpen(true)}} remove={()=>{if(!selectedDaily)return;setData(d=>({...d,dailies:d.dailies.filter(x=>x.id!==selectedDaily.id)}));setSelectedDaily(null)}}/>
    <FilterSheet open={filterOpen} close={()=>setFilterOpen(false)} value={historyFilter} setValue={setHistoryFilter}/>
    <SettingsDialog open={settingsOpen} close={()=>setSettingsOpen(false)} data={data} setData={setData}/>
  </main>
}

function Logo(){return <div className="logo">DoseKey</div>}
function Header({title,back,action}:{title?:React.ReactNode;back?:()=>void;action?:React.ReactNode}){return <header className={"topbar "+(back?"with-back":"")}>{back&&<button onClick={back} className="circle-btn" aria-label="Geri"><ArrowLeft/></button>}{title?<h1>{title}</h1>:!back&&<Logo/>}<div className="top-action">{action}</div></header>}
function BottomNav({screen,setScreen}:{screen:Screen;setScreen:(s:Screen)=>void}){const items=[["today","Bugün",Home],["history","Geçmiş",History],["progress","İlerleme",BarChart3],["plan","Plan",CalendarDays]] as const;return <nav className="bottom-nav">{items.map(([id,label,Icon])=><button key={id} className={screen===id?"active":""} onClick={()=>setScreen(id)}><Icon/><span>{label}</span></button>)}</nav>}

function Today({data,active,openDose,openCheck,openSettings,toggleTheme,go,goMetric}:{data:Store;active:Period;openDose:()=>void;openCheck:()=>void;openSettings:()=>void;toggleTheme:()=>void;go:(s:Screen)=>void;goMetric:(id:string)=>void}){
 const last=sortedDoses(data.doses)[0],byDate=[...data.dailies].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id),next=nextDose(active,data.doses);
 // Son kayıtta kilo girilmemiş olabilir; kilo girilen en yeni kaydı göster.
 const lastWeighed=byDate.find(d=>Number.isFinite(d.weight));
 const days=next?Math.round((new Date(next+"T12:00:00").getTime()-new Date(dateKey()+"T12:00:00").getTime())/86400000):0;
 return <div className="page today-page"><Header action={<div className="header-tools"><button className="circle-btn" aria-label={data.dark?"Açık moda geç":"Koyu moda geç"} onClick={toggleTheme}>{data.dark?<Sun/>:<Moon/>}</button><button className="circle-btn profile-trigger" aria-label="Profilim" onClick={openSettings}><UserRound/></button></div>}/><h1 className="greeting">{greetingFor(data.profile.name)}</h1><p className="page-date">{fullPretty(dateKey())}</p>
  <section className="active-card"><div><h2>{active.medication}</h2><p>{active.dose}{active.amount&&" / "+active.amount}</p><Status/></div><button aria-label="İlerlemeyi aç" onClick={()=>go("progress")} className="chart-orbit"><BarChart3/></button><button className="next-dose" onClick={()=>go("plan")}><CalendarDays/><span><b>{!next?"Plansız kullanım":days===0?"Bugün doz günün":days>0?`Sonraki dozuna ${days} gün var`:"Planlanan tarih geçti"}</b><small>{next?pretty(next)+" · "+active.time.replace(":","."):"Kayıtlarını istediğin zaman ekleyebilirsin"}</small></span><ChevronRight/></button></section>
  <div className="primary-actions"><button className="primary" onClick={openDose}><Check/>Dozumu kullandım</button><button onClick={openCheck}><FileText/>Günlük kayıt ekle</button></div>
  <div className="metric-grid"><Metric icon={Activity} label="İştah · Ort." value={dailyAverage(data.dailies,"appetite")+"/5"} onClick={()=>goMetric("appetite")}/><Metric icon={Zap} label="Enerji · Ort." value={dailyAverage(data.dailies,"energy")+"/5"} violet onClick={()=>goMetric("energy")}/><Metric icon={Scale} label="Kilo" value={(lastWeighed?.weight?.toLocaleString("tr-TR")??"—")+" kg"} teal onClick={()=>goMetric("weight")}/></div>
  {last&&<button className="last-use" onClick={()=>go("history")}><span className="icon-disc"><Clock3/></span><span><b>Son kullanım</b><strong>{pretty(last.date)} · {last.time.replace(":",".")}</strong><small>{last.site}</small></span><ChevronRight/></button>}
 </div>
}
function Metric({icon:Icon,label,value,violet,teal,onClick}:{icon:typeof Activity;label:string;value:string;violet?:boolean;teal?:boolean;onClick:()=>void}){return <button className="metric" aria-label={label+" ilerlemesini aç"} onClick={onClick}><span className={"metric-icon "+(violet?"violet":teal?"teal":"")}><Icon/></span><small>{label}</small><b>{value}</b></button>}
function Status(){return <span className="status"><i/>Aktif dönem</span>}

function HistoryScreen({data,filter,openFilter,select,selectDaily,openDose}:{data:Store;filter:string;openFilter:()=>void;select:(d:Dose)=>void;selectDaily:(d:Daily)=>void;openDose:()=>void}){
 const [mode,setMode]=useState("list"),[month,setMonth]=useState(dateKey().slice(0,7)),[day,setDay]=useState("");
 const moveMonth=(n:number)=>{const d=new Date(month+"-01T12:00:00");d.setMonth(d.getMonth()+n);setMonth(dateKey(d).slice(0,7));setDay("")};
 const ds=["Tümü","Doz"].includes(filter)?sortedDoses(data.doses):[];
 const dailyRows=data.dailies.filter(d=>filter!=="Doz"&&(filter!=="Kilo"||d.weight!==undefined)&&(filter!=="Belirtiler"||d.symptoms.some(s=>s!=="Yok")));
 const allDates=Array.from(new Set([...ds.map(d=>d.date),...dailyRows.map(d=>d.date)])).sort().reverse();
 const dates=allDates.filter(d=>d.startsWith(month)&&(mode!=="calendar"||!day||day===d));
 return <div className="page history-page"><Header title="Geçmiş" action={<button aria-label="Geçmişi filtrele" className="filter-button" onClick={openFilter}><Filter/>{filter!=="Tümü"&&<i/>}</button>}/><Tabs value={mode} onValueChange={v=>{setMode(v);setDay("")}}><TabsList className="history-tabs"><TabsTrigger value="list">Liste</TabsTrigger><TabsTrigger value="calendar">Takvim</TabsTrigger></TabsList></Tabs><div className="month-switch"><button aria-label="Önceki ay" onClick={()=>moveMonth(-1)}><ChevronRight className="rotate-180"/></button><b>{new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric"}).format(new Date(month+"-01T12:00:00"))}</b><button aria-label="Sonraki ay" onClick={()=>moveMonth(1)}><ChevronRight/></button></div>
  {mode==="calendar"&&<div className="calendar-grid">{["Pt","Sa","Ça","Pe","Cu","Ct","Pz"].map(x=><small key={x}>{x}</small>)}{Array.from({length:(new Date(month+"-01T12:00:00").getDay()+6)%7},(_,i)=><span key={"blank"+i}/>)}{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>{const date=month+"-"+String(i+1).padStart(2,"0");return <button key={date} aria-label={pretty(date)} className={(allDates.includes(date)?"has-record ":"")+(day===date?"selected":"")} onClick={()=>setDay(day===date?"":date)}>{i+1}</button>})}</div>}
  <div className="history-groups">{dates.length?dates.map(date=>{const doses=ds.filter(d=>d.date===date),dailies=dailyRows.filter(d=>d.date===date);return <section className="history-group" key={date}><div className="group-title"><b>{fullPretty(date)}</b><span>{doses.length+dailies.length} kayıt</span></div>{doses.map(d=><button className="history-dose" key={d.id} onClick={()=>select(d)}><span className="pill-disc"><Pill/></span><span><b>{d.time.replace(":",".")}</b></span><span className="grow"><strong>{d.medication} · {d.dose}{d.amount&&" / "+d.amount}</strong><small>{d.site}</small></span><ChevronRight/></button>)}{dailies.map(d=><button key={d.id} className="history-daily" onClick={()=>selectDaily(d)}><span className="daily-disc"><FileText/></span><span><b>Günlük kayıt</b><small>İştah {d.appetite}/5 · Enerji {d.energy}/5{d.weight?" · "+d.weight.toLocaleString("tr-TR")+" kg":""}</small></span><ChevronRight/></button>)}</section>}):<p className="empty-state">Bu tarih ve filtre için kayıt yok.</p>}</div>
  <button aria-label="Doz kaydı ekle" className="fab" onClick={openDose}><Plus/></button>
 </div>
}

function Progress({data,active,filter,setFilter,doses,select}:{data:Store;active:Period;filter:string;setFilter:(s:string)=>void;doses:Dose[];select:(d:Dose)=>void}){
 const [range,setRange]=useState(28),[metric,setMetric]=useState<ProgressMetric|null>(null);
 const metricTrigger=useRef<HTMLButtonElement|null>(null);
 const openMetric=(value:ProgressMetric,event:React.MouseEvent<HTMLButtonElement>)=>{metricTrigger.current=event.currentTarget;setMetric(value)};
 const period=filter==="all"?null:data.periods.find(p=>p.id===(filter==="active"?active.id:Number(filter)));
 const from=range?addDays(dateKey(),-range+1):"0000-01-01";
 const entries=data.dailies.filter(d=>d.date>=from&&d.date<=dateKey()&&(!period||(d.date>=period.start&&(!period.end||d.date<=period.end)))).sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);
 const weights=entries.filter(d=>d.weight!==undefined).map(d=>({date:pretty(d.date).replace(/ \d{4}$/, ""),value:d.weight!}));
 const average=(key:"appetite"|"energy")=>dailyAverage(entries,key);
 const symptoms=Array.from(new Set(entries.flatMap(d=>d.symptoms).filter(s=>s!=="Yok")));
 const usage=sortedDoses(doses.filter(d=>d.date>=from&&d.date<=dateKey()));
 return <div className="page progress-page"><Header title="İlerleme"/><Select value={filter} onValueChange={setFilter}><SelectTrigger className="period-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">{active.dose} / {active.amount} · Aktif dönem</SelectItem>{data.periods.filter(p=>!p.active).map(p=><SelectItem value={String(p.id)} key={p.id}>{p.dose} / {p.amount}</SelectItem>)}<SelectItem value="all">Tüm dönemler</SelectItem></SelectContent></Select>
  <div className="range-tabs">{[[28,"4 hafta"],[56,"8 hafta"],[0,"Tümü"]].map(([n,label])=><button key={n} className={range===n?"active":""} onClick={()=>setRange(Number(n))}>{label}</button>)}</div>
  <section id="weight" tabIndex={-1} className="progress-card metric-history-card"><button className="metric-history-trigger" aria-label="Kilo kayıtlarını gör" aria-haspopup="dialog" onClick={e=>openMetric("weight",e)}/><CardTitle icon={Scale} title="Kilo"/><ChevronRight className="metric-history-chevron" aria-hidden="true"/>{weights.length?<><div className="weight-head"><div><b>{weights[0].value.toLocaleString("tr-TR")} kg</b><small>{weights[0].date}</small></div><div><strong>{(weights.at(-1)!.value-weights[0].value).toLocaleString("tr-TR",{maximumFractionDigits:1})} kg değişim</strong><b>{weights.at(-1)!.value.toLocaleString("tr-TR")} kg</b><small>{weights.at(-1)!.date}</small></div></div><BigChart points={weights}/></>:<p className="empty-state">Bu aralıkta kilo kaydı yok.</p>}</section>
  <div className="mini-grid"><MiniCard onOpen={e=>openMetric("appetite",e)} id="appetite" title="İştah" value={"Bugün ort. "+average("appetite")+" / 5"} icon={Activity} data={entries.map((d,i)=>({x:i,v:d.appetite}))}/><MiniCard onOpen={e=>openMetric("energy",e)} id="energy" title="Enerji" value={"Bugün ort. "+average("energy")+" / 5"} icon={Zap} data={entries.map((d,i)=>({x:i,v:d.energy}))}/></div>
  <section id="symptoms" className="progress-card metric-history-card"><button className="metric-history-trigger" aria-label="Belirti kayıtlarını gör" aria-haspopup="dialog" onClick={e=>openMetric("symptoms",e)}/><CardTitle icon={Activity} title="Belirtiler"/><ChevronRight className="metric-history-chevron" aria-hidden="true"/>{symptoms.length?symptoms.map(s=><Symptom key={s} label={s} n={entries.filter(d=>d.symptoms.includes(s)).length}/>):<p className="empty-state">Bu aralıkta belirti kaydı yok.</p>}</section>
  <section className="progress-card"><CardTitle icon={CalendarDays} title="Doz dönemleri"/>{(period?[period]:data.periods).map(p=><p key={p.id} className="period-summary"><b>{p.medication} · {p.dose}{p.amount&&" / "+p.amount}</b><span>{pretty(p.start)} — {p.end?pretty(p.end):"Devam ediyor"}</span><small><Clock3/>{elapsed(p.start,p.end)+1} gün <Syringe/> {data.doses.filter(d=>d.periodId===p.id).length} kullanım</small></p>)}</section>
  <section className="progress-card"><CardTitle icon={History} title="Kullanım kayıtları"/>{usage.length?usage.map(d=><button onClick={()=>select(d)} className="usage-row" key={d.id}><span>{pretty(d.date)} · {d.time.replace(":",".")}</span><span>{d.site}</span><ChevronRight/></button>):<p className="empty-state">Bu aralıkta kullanım kaydı yok.</p>}</section>
  <MetricHistory metric={metric} entries={entries} context={(period?period.medication+" · "+doseOptionLabel(period):"Tüm dönemler")+" · "+(range?range/7+" hafta":"Tüm zamanlar")} close={()=>setMetric(null)} restoreFocus={()=>metricTrigger.current?.focus({preventScroll:true})}/>
 </div>
}
type ProgressMetric="weight"|"appetite"|"energy"|"symptoms";
const metricTitles:Record<ProgressMetric,string>={weight:"Kilo",appetite:"İştah",energy:"Enerji",symptoms:"Belirti"};
function MetricHistory({metric,entries,context,close,restoreFocus}:{metric:ProgressMetric|null;entries:Daily[];context:string;close:()=>void;restoreFocus:()=>void}){
 const rows=[...entries].filter(d=>metric==="weight"?typeof d.weight==="number"&&Number.isFinite(d.weight):metric==="appetite"||metric==="energy"?Number.isFinite(d[metric]):true).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);
 const title=metric?metricTitles[metric]:"";
 const value=(d:Daily)=>metric==="weight"?d.weight!.toLocaleString("tr-TR")+" kg":metric==="appetite"?d.appetite+" / 5":metric==="energy"?d.energy+" / 5":d.symptoms.length?d.symptoms.filter(s=>s!=="Yok").join(", ")||"Belirti yok":"Belirti eklenmedi";
 return <Dialog open={metric!==null} onOpenChange={o=>!o&&close()}><DialogContent className="sheet-dialog metric-records-dialog" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();restoreFocus()}}>
  <div className="metric-records-header"><div className="sheet-handle"/><button className="sheet-close" aria-label="Kayıt listesini kapat" onClick={close}><X/></button><DialogTitle>{title} kayıtları</DialogTitle><DialogDescription>{context}</DialogDescription><p>{rows.length} kayıt · En yeniden eskiye</p></div>
  <div className="metric-records-body">{rows.length?<Table className="metric-records-table"><TableHeader><TableRow><TableHead scope="col">Tarih / saat</TableHead><TableHead scope="col">{metric==="symptoms"?"Belirtiler":title}</TableHead></TableRow></TableHeader><TableBody>{rows.map(d=><TableRow key={d.id}><TableCell><time dateTime={d.date}>{pretty(d.date)}</time><small className="metric-record-time">{addedTime(d)?addedTime(d)+"’da eklendi":"Saat bilgisi yok"}</small></TableCell><TableCell>{value(d)}</TableCell></TableRow>)}</TableBody></Table>:<p className="empty-state">Seçili dönem ve tarih aralığında {title.toLocaleLowerCase("tr-TR")} kaydı yok.</p>}</div>
 </DialogContent></Dialog>
}

function CardTitle({icon:Icon,title}:{icon:typeof Activity;title:string}){return <div className="card-title"><span className="icon-disc"><Icon/></span><b>{title}</b></div>}
function BigChart({points}:{points:{date:string;value:number}[]}){return <div className="big-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{left:-12,right:6,top:10}}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={["dataMin - 1","dataMax + 1"]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip/><Area dataKey="value" name="Kilo (kg)" type="monotone" stroke="#0c8cff" strokeWidth={3} dot={{r:4}} fill="#0c8cff33"/></AreaChart></ResponsiveContainer></div>}
function MiniCard({id,title,value,icon:Icon,data,onOpen}:{id:string;title:string;value:string;icon:typeof Activity;data:{x:number;v:number}[];onOpen:(event:React.MouseEvent<HTMLButtonElement>)=>void}){return <section id={id} tabIndex={-1} className="progress-card mini-card metric-history-card"><button className="metric-history-trigger" aria-label={title+" kayıtlarını gör"} aria-haspopup="dialog" onClick={onOpen}/><CardTitle icon={Icon} title={title}/><ChevronRight className="metric-history-chevron" aria-hidden="true"/><b>{value}</b><div><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><YAxis hide domain={[1,5]}/><Area dataKey="v" type="monotone" stroke="#1c91ff" strokeWidth={2} dot={{r:3}} fill="transparent"/></AreaChart></ResponsiveContainer></div><small>{data.length} kayıt</small></section>}
function Symptom({label,n}:{label:string;n:number}){return <div className="symptom"><span>{label}</span><i><b style={{width:Math.min(100,n/3*100)+"%"}}/></i><strong>{n}</strong></div>}

function Plan({data,active,add,toggleReminder,setReminderTime,select}:{data:Store;active:Period;add:()=>void;toggleReminder:()=>void;setReminderTime:(time:string)=>void;select:(id:number)=>void}){const next=nextDose(active,data.doses);return <div className="page plan-page"><Header title="Plan" action={<button aria-label="Yeni doz dönemi" className="fab-inline" onClick={add}><Plus/></button>}/><section className="plan-main"><h2>{active.medication}</h2><p>{active.dose}{active.amount&&" / "+active.amount}</p><Status/><div className="plan-info"><RotateCw/><span><b>{active.interval}</b><small>{active.time.replace(":",".")}</small></span></div><div className="plan-info"><CalendarDays/><span><b>Sonraki doz</b><small>{next?pretty(next):"Plansız kullanım"}</small></span></div></section>
 <button className="reminder-card" onClick={toggleReminder}><Bell/><span><b>Doz günü bildirimi</b><small>{data.profile.reminderTime.replace(":",".")}</small></span><span className={"switch "+(data.profile.reminders?"on":"")}><i/></span></button>{data.profile.reminders&&<Field label="Bildirim saati"><Input aria-label="Bildirim saati" type="time" value={data.profile.reminderTime} onInput={event=>setReminderTime((event.target as HTMLInputElement).value)} className="control"/></Field>}
 <p className="tracker-note">Bildirim tercihin bu cihazda saklanır. Uygulama kapalıyken telefon bildirimi gönderimi henüz bağlı değil.</p><h2 className="section-heading">Doz dönemleri</h2><div className="periods">{data.periods.slice().reverse().map(p=><button onClick={()=>select(p.id)} className={"period-item "+(p.active?"active":"")} key={p.id}><span className="period-dot"/><span><b>{p.dose}{p.amount&&" / "+p.amount}</b><small>{pretty(p.start)} — {p.end?pretty(p.end):"Devam ediyor"}</small><small>{elapsed(p.start,p.end)+1} gün · {data.doses.filter(d=>d.periodId===p.id).length} kullanım</small></span><ChevronRight/></button>)}</div>
 </div>}

function Onboarding({data,setData,preview=false,exitPreview}:{data:Store;setData:React.Dispatch<React.SetStateAction<Store>>;preview?:boolean;exitPreview?:()=>void}){
 const [step,setStep]=useState(0),[name,setName]=useState(data.profile.name),[gender,setGender]=useState(data.profile.gender??""),[birthDate,setBirthDate]=useState(data.profile.birthDate??""),[med,setMed]=useState("Mounjaro"),[dose,setDose]=useState(""),[amount,setAmount]=useState(""),[interval,setInterval]=useState("Her 7 günde bir"),[startDate,setStartDate]=useState(dateKey()),[reminders,setReminders]=useState(false),[reminderTime,setReminderTime]=useState("09:00"),[search,setSearch]=useState(""),[customDays,setCustomDays]=useState("7");
 const finish=()=>{if(preview){exitPreview?.();return}const m=medicationOptions.find(x=>x.name===med);setData(d=>({...d,profile:{...d.profile,name:name.trim(),gender,birthDate,reminders,reminderTime,onboarded:true},periods:[{...d.periods[0],id:Date.now(),medication:med,ingredient:m?.ingredient||"",dose:dose.trim(),amount:med==="Rybelsus"?"":amount.trim(),interval:interval==="Her N günde bir"?`Her ${Number(customDays)} günde bir`:interval,start:startDate,end:undefined,active:true}]}))};
 return <main className="onboarding"><div className="onboard-phone"><Header back={step?()=>setStep(step-1):undefined}/><div className="dots">{[0,1,2,3,4,5].map(n=><i key={n} className={n===step?"active":""}/>)}</div>
  {step===0&&<div className="onboard-content"><h1>DoseKey’e hoş geldin</h1><p>Seni biraz tanıyalım.</p><ProfileFields name={name} gender={gender} birthDate={birthDate} setName={setName} setGender={setGender} setBirthDate={setBirthDate}/></div>}
  {step===1&&<div className="onboard-content"><h1>Hangi ilacı takip edeceksin?</h1><p>Takip edeceğin ilacı listeden seç.</p><Input placeholder="İlaç ara" value={search} onChange={e=>setSearch(e.target.value)} className="control"/><div className="choice-list">{medicationOptions.filter(m=>m.name.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))).map(m=><button key={m.name} className={med===m.name?"selected":""} onClick={()=>{setMed(m.name);setDose("");setAmount("")}}><span className="pill-disc"><Pill/></span><span><b>{m.name}</b><small>{m.ingredient}</small></span><i>{med===m.name&&<Check/>}</i></button>)}</div></div>}
  {step===2&&<div className="onboard-content"><h1>Kullandığın dozu seç</h1><p>{med} · Kendi ürünündeki değeri seç.</p><DosePicker med={med} dose={dose} amount={amount} onChange={(d,a)=>{setDose(d);setAmount(a)}}/></div>}
  {step===3&&<div className="onboard-content"><h1>Ne sıklıkla kullanıyorsun?</h1><p>Kullanım aralığını sen belirlersin.</p><div className="radio-list">{["Her gün","Her 7 günde bir","Her N günde bir","Plansız kullanım"].map(x=><button className={interval===x?"selected":""} key={x} onClick={()=>setInterval(x)}><span>{x}</span><i>{interval===x&&<Check/>}</i></button>)}</div>{interval==="Her N günde bir"&&<Field label="Kaç günde bir?"><Input type="number" min="1" max="365" value={customDays} onChange={e=>setCustomDays(e.target.value)} className="control"/></Field>}</div>}
  {step===4&&<div className="onboard-content"><h1>İlk kullanım günün ne zaman?</h1><p>İlaca başladığın veya başlayacağın tarihi seç.</p><Field label="İlk kullanım tarihi"><Input type="date" value={startDate} onInput={e=>setStartDate((e.target as HTMLInputElement).value)} className="control"/></Field><p className="info-note">Sonraki doz tarihi bu gün ve seçtiğin kullanım aralığına göre hesaplanır.</p></div>}
  {step===5&&<div className="onboard-content"><h1>Hatırlatma ister misin?</h1><p>Telefon uygulaması doz gününde seçtiğin saatte sana hatırlatabilir.</p><button className="reminder-option" onClick={()=>setReminders(!reminders)}><Bell/><span>Doz günü bildirimi</span><span className={"switch "+(reminders?"on":"")}><i/></span></button>{reminders&&<Field label="Bildirim saati"><Input aria-label="Bildirim saati" type="time" value={reminderTime} onInput={event=>setReminderTime((event.target as HTMLInputElement).value)} className="control"/></Field>}<div className="notification-preview"><span className="notification-logo" aria-hidden="true">D</span><span className="notification-copy"><b>Bugün doz günün</b><small>DoseKey · {reminderTime.replace(":",".")}</small></span></div></div>}
  <div className="onboard-footer"><Button disabled={(step===0&&(!name.trim()||!gender||!validBirthDate(birthDate)))||(step===2&&!dose.trim())||(step===3&&interval==="Her N günde bir"&&(!Number.isInteger(Number(customDays))||Number(customDays)<1||Number(customDays)>365))||(step===4&&!validDate(startDate))} onClick={()=>step===5?finish():setStep(step+1)} className="primary wide">{step===5?"Planımı oluştur":"Devam"}</Button></div>
 </div></main>
}

function DoseFlow({open,close,active,periods,editing,save}:{open:boolean;close:()=>void;active:Period;periods:Period[];editing:Dose|null;save:(d:Omit<Dose,"id"|"createdAt">)=>void}){
 // Gövde yalnızca açıkken monte edilir, böylece alanlar her açılışta kendiliğinden sıfırlanır.
 return <Dialog open={open} onOpenChange={o=>!o&&close()}><DialogContent aria-describedby={undefined} showCloseButton={false} className="full-dialog">{open&&<DoseFlowBody close={close} active={active} periods={periods} editing={editing} save={save}/>}</DialogContent></Dialog>
}
function DoseFlowBody({close,active,periods,editing,save}:{close:()=>void;active:Period;periods:Period[];editing:Dose|null;save:(d:Omit<Dose,"id"|"createdAt">)=>void}){
 const [other,setOther]=useState(!!editing),[date,setDate]=useState(editing?.date??dateKey()),[time,setTime]=useState(editing?.time??timeKey()),[site,setSite]=useState(editing?.site??"Belirtilmedi"),[note,setNote]=useState(editing?.note??""),[periodId,setPeriodId]=useState(editing?.periodId??active.id),[error,setError]=useState("");
 const period=periods.find(p=>p.id===periodId)??active;
 const done=()=>{if(!date||!time||date>dateKey()){setError("Geçerli bir kullanım tarihi ve saati gir. Gelecek tarih için Plan ekranını kullan.");return}save({medication:period.medication,ingredient:period.ingredient,dose:period.dose,amount:period.amount,date,time,site:period.medication==="Rybelsus"?"Ağızdan":site,note,periodId:period.id});close()};
 return <div className="flow-page"><Header title={<DialogTitle asChild><span>{editing?"Kaydı düzenle":"Doz kaydı"}</span></DialogTitle>} back={close}/><Field label="İlaç ve doz dönemi"><Select value={String(periodId)} onValueChange={v=>setPeriodId(Number(v))}><SelectTrigger className="control"><SelectValue/></SelectTrigger><SelectContent>{periods.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.medication} · {p.dose}{p.amount&&" / "+p.amount}</SelectItem>)}</SelectContent></Select></Field><h2>Kullanım zamanı</h2><div className="segmented"><button className={!other?"active":""} onClick={()=>{setOther(false);setDate(dateKey());setTime(timeKey())}}>Şimdi</button><button className={other?"active":""} onClick={()=>setOther(true)}>Başka bir zaman</button></div><div className="date-time-grid"><Field label="Tarih"><Input type="date" max={dateKey()} value={date} onInput={e=>{setOther(true);setDate((e.target as HTMLInputElement).value)}} className="control"/></Field><Field label="Saat"><Input type="time" value={time} onInput={e=>setTime((e.target as HTMLInputElement).value)} className="control"/></Field></div>{period.medication!=="Rybelsus"&&<><h2>Uygulama bölgesi</h2><div className="site-grid">{["Sol karın","Sağ karın","Sol uyluk","Sağ uyluk","Sol kol","Sağ kol","Belirtilmedi"].map(x=><button className={site===x?"active":""} key={x} onClick={()=>setSite(x)}>{x}</button>)}</div></>}<Field label="Not · isteğe bağlı"><Textarea value={note} onChange={e=>setNote(e.target.value)} className="note"/></Field>{error&&<p role="alert" className="form-error">{error}</p>}<Button className="primary wide" onClick={done}>{editing?"Değişiklikleri kaydet":"Kaydı tamamla"}</Button></div>
}

function DailyFlow({open,close,editing,save}:{open:boolean;close:()=>void;editing:Daily|null;save:(d:Omit<Daily,"id"|"createdAt">)=>void}){
 return <Dialog open={open} onOpenChange={o=>!o&&close()}><DialogContent showCloseButton={false} className="sheet-dialog" aria-describedby={undefined}>{open&&<DailyFlowBody close={close} editing={editing} save={save}/>}</DialogContent></Dialog>
}
function DailyFlowBody({close,editing,save}:{close:()=>void;editing:Daily|null;save:(d:Omit<Daily,"id"|"createdAt">)=>void}){
 const [step,setStep]=useState(0),[appetite,setAppetite]=useState([editing?.appetite??2]),[energy,setEnergy]=useState([editing?.energy??3]),[symptoms,setSymptoms]=useState<string[]>(editing?.symptoms??[]),[weight,setWeight]=useState(editing?.weight?.toString()??""),[dailyDate,setDailyDate]=useState(editing?.date??dateKey()),[error,setError]=useState("");
 const finish=()=>{if(!dailyDate||dailyDate>dateKey()||(weight.trim()&&(!Number.isFinite(Number(weight.replace(",",".")))||Number(weight.replace(",","."))<=0))){setError("Tarih ve kilo alanlarını kontrol et.");return}save({date:dailyDate,appetite:appetite[0],energy:energy[0],symptoms,weight:Number(weight.replace(",","."))||undefined});close();setStep(0)};
 return <><div className="sheet-handle"/><button className="sheet-close" aria-label="Kapat" onClick={close}><X/></button><DialogTitle>{editing?"Günlük kaydı düzenle":"Günlük kayıt"} <span>{step+1} / 4</span></DialogTitle>{step===0&&<details><summary>{dailyDate===dateKey()?"Bugün":pretty(dailyDate)} · Tarihi değiştir</summary><Field label="Kayıt tarihi"><Input className="control" type="date" max={dateKey()} value={dailyDate} onInput={e=>setDailyDate((e.target as HTMLInputElement).value)}/></Field></details>}
  {step===0&&<SliderStep title="Bugün iştahın nasıldı?" value={appetite} setValue={setAppetite}/>}
  {step===1&&<SliderStep title="Bugün enerjin nasıldı?" value={energy} setValue={setEnergy}/>}
  {step===2&&<div className="daily-step"><h3>Bugün bir belirti oldu mu?</h3><div className="symptom-grid">{["Bulantı","Kabızlık","İshal","Reflü","Baş ağrısı","Yok"].map(x=><button key={x} className={symptoms.includes(x)?"active":""} onClick={()=>setSymptoms(x==="Yok"?["Yok"]:symptoms.includes(x)?symptoms.filter(s=>s!==x):[...symptoms.filter(s=>s!=="Yok"),x])}>{x}</button>)}</div></div>}
  {step===3&&<div className="daily-step"><h3>Bugünkü kilon</h3><div className="weight-input"><Input aria-label="Bugünkü kilon" value={weight} onChange={e=>setWeight(e.target.value)} inputMode="decimal"/><span>kg</span></div><button className="skip-link" onClick={()=>setWeight("")}>Atla</button></div>}
  {error&&<p role="alert" className="form-error">{error}</p>}<div className="daily-actions">{step>0&&<Button variant="outline" onClick={()=>setStep(step-1)}>Geri</Button>}<Button className="primary wide" onClick={()=>step===3?finish():setStep(step+1)}>{step===3?(editing?"Değişiklikleri kaydet":"Kaydı tamamla"):"Devam"}<ChevronRight/></Button></div>
 </>
}
function SliderStep({title,value,setValue}:{title:string;value:number[];setValue:(v:number[])=>void}){return <div className="daily-step"><h3>{title}</h3><div className="number-choices">{[1,2,3,4,5].map(n=><button onClick={()=>setValue([n])} className={value[0]===n?"active":""} key={n}>{n}</button>)}</div><div className="range-labels"><span>Çok düşük</span><span>Çok yüksek</span></div><Slider min={1} max={5} step={1} value={value} onValueChange={setValue}/></div>}

function PeriodFlow({open,close,active,save}:{open:boolean;close:()=>void;active:Period;save:(p:Omit<Period,"id">)=>void}){
 return <Dialog open={open} onOpenChange={o=>!o&&close()}><DialogContent showCloseButton={false} className="full-dialog" aria-describedby={undefined}>{open&&<PeriodFlowBody close={close} active={active} save={save}/>}</DialogContent></Dialog>
}
function PeriodFlowBody({close,active,save}:{close:()=>void;active:Period;save:(p:Omit<Period,"id">)=>void}){
 const [dose,setDose]=useState(active.dose),[amount,setAmount]=useState(active.amount),[start,setStart]=useState(dateKey()),[interval,setInterval]=useState(!["Her gün","Her 7 günde bir","Plansız kullanım"].includes(active.interval)?"Her N günde bir":active.interval),[time,setTime]=useState(active.time),[med,setMed]=useState(active.medication),[customDays,setCustomDays]=useState(active.interval.match(/\d+/)?.[0]||"7"),[error,setError]=useState("");
 const finish=()=>{if(!dose.trim()||!start||start<=active.start||start>dateKey()||!time||(interval==="Her N günde bir"&&(!Number.isInteger(Number(customDays))||Number(customDays)<1||Number(customDays)>365))){setError("Dozu, saati ve aralığı kontrol et. Yeni dönem mevcut dönemden sonra, en geç bugün başlamalı.");return}save({medication:med,ingredient:medicationOptions.find(m=>m.name===med)?.ingredient||"",dose:dose.trim(),amount:med==="Rybelsus"?"":amount.trim(),start,interval:interval==="Her N günde bir"?`Her ${Number(customDays)} günde bir`:interval,day:new Intl.DateTimeFormat("tr-TR",{weekday:"long"}).format(new Date(start+"T12:00:00")),time,active:true});close()};
 return <div className="flow-page"><Header title={<DialogTitle asChild><span>Yeni doz dönemi</span></DialogTitle>} back={close}/><Field label="İlaç"><Select value={med} onValueChange={m=>{setMed(m);setDose("");setAmount("")}}><SelectTrigger className="control"><SelectValue/></SelectTrigger><SelectContent>{medicationOptions.map(m=><SelectItem key={m.name} value={m.name}>{m.name}</SelectItem>)}</SelectContent></Select></Field><DosePicker med={med} dose={dose} amount={amount} existing={active} onChange={(d,a)=>{setDose(d);setAmount(a)}}/><Field label="Başlangıç tarihi"><Input type="date" min={addDays(active.start,1)} max={dateKey()} value={start} onInput={e=>setStart((e.target as HTMLInputElement).value)} className="control"/></Field><Field label="Tekrar"><Select value={interval} onValueChange={setInterval}><SelectTrigger className="control"><SelectValue/></SelectTrigger><SelectContent>{["Her gün","Her 7 günde bir","Her N günde bir","Plansız kullanım"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field>{interval==="Her N günde bir"&&<Field label="Kaç günde bir?"><Input type="number" min="1" max="365" value={customDays} onChange={e=>setCustomDays(e.target.value)} className="control"/></Field>}<div><Field label="Saat"><Input type="time" value={time} onInput={e=>setTime((e.target as HTMLInputElement).value)} className="control"/></Field></div><p className="info-note">Doz dönemi değiştirmek zorunlu değil. Yeni dönem eklersen önceki dönem bir gün önce sona erer; kayıtların korunur.</p>{error&&<p role="alert" className="form-error">{error}</p>}<Button className="primary wide" onClick={finish}>Dönemi oluştur</Button></div>
}

function DoseDetail({dose,period,close,edit,remove}:{dose:Dose|null;period?:Period;close:()=>void;edit:()=>void;remove:()=>void}){return <Dialog open={!!dose} onOpenChange={o=>!o&&close()}><DialogContent aria-describedby={undefined} showCloseButton={false} className="full-dialog">{dose&&<div className="flow-page detail-page"><Header title={<DialogTitle asChild><span>Doz kaydı detayı</span></DialogTitle>} back={close} /><section className="detail-hero"><span className="pill-disc"><Pill/></span><span><b>{dose.medication}</b><small>{dose.dose} / {dose.amount}</small></span><span className="muted">{period?.active?"Aktif dönem":"Geçmiş dönem"}</span><p><CalendarDays/>{pretty(dose.date)} · {dose.time.replace(":",".")}</p></section><DetailSection title="İlaç bilgileri" rows={[["Marka",dose.medication],["Etken madde",dose.ingredient],["Uygulanan doz",dose.dose],["Sunum",dose.dose+" / "+dose.amount],["Form",dose.medication==="Rybelsus"?"Tablet":"Enjeksiyon"]]}/><DetailSection title="Kullanım bilgileri" rows={[["Kullanım tarihi",pretty(dose.date)],["Kullanım saati",dose.time.replace(":",".")],["Uygulama bölgesi",dose.site],["Not",dose.note||"Not eklenmedi"]]}/>{period&&<DetailSection title="Bağlı plan ve dönem" rows={[["Plan",period.medication+" planı"],["Doz dönemi",period.dose+" / "+period.amount],["Dönem başlangıcı",pretty(period.start)],["Tekrar aralığı",period.interval],["Planlanan zaman",period.day+" · "+period.time.replace(":",".")]]}/>}<details className="record-metadata"><summary>Kayıt bilgileri</summary><DetailSection title="Ayrıntılar" rows={[["Kayıt yöntemi","Manuel"],["Saat dilimi",Intl.DateTimeFormat().resolvedOptions().timeZone],["Kayıt kimliği","DSK-"+String(dose.id).slice(-8)],["Kayıt oluşturma",dose.createdAt]]}/></details><div className="record-actions"><Button variant="outline" className="outline-wide" onClick={edit}><Pencil/>Kaydı düzenle</Button><DeleteConfirm title="Doz kaydı silinsin mi?" description="Bu kullanım kaydı geçmişten kaldırılacak ve sonraki doz hesabı kalan kayıtlara göre yenilenecek." onDelete={remove}/></div></div>}</DialogContent></Dialog>}

function DailyDetail({daily,close,edit,remove}:{daily:Daily|null;close:()=>void;edit:()=>void;remove:()=>void}){return <Dialog open={!!daily} onOpenChange={o=>!o&&close()}><DialogContent aria-describedby={undefined} showCloseButton={false} className="full-dialog">{daily&&<div className="flow-page detail-page"><Header title={<DialogTitle asChild><span>Günlük kayıt detayı</span></DialogTitle>} back={close}/><section className="detail-hero daily-detail-hero"><span className="daily-disc"><FileText/></span><span><b>Günlük durum</b><small>{addedTime(daily)?addedTime(daily)+"’da eklendi":"Saat bilgisi yok"}</small></span><p><CalendarDays/>{pretty(daily.date)}</p></section><DetailSection title="Günlük durum" rows={[["İştah",daily.appetite+" / 5"],["Enerji",daily.energy+" / 5"],["Kilo",daily.weight?daily.weight.toLocaleString("tr-TR")+" kg":"Eklenmedi"],["Belirtiler",daily.symptoms.join(", ")||"Yok"]]}/><details className="record-metadata"><summary>Kayıt bilgileri</summary><DetailSection title="Ayrıntılar" rows={[["Kayıt yöntemi","Manuel"],["Kayıt kimliği","GNL-"+String(daily.id).slice(-8)],["Kayıt oluşturma",daily.createdAt]]}/></details><div className="record-actions"><Button variant="outline" className="outline-wide" onClick={edit}><Pencil/>Kaydı düzenle</Button><DeleteConfirm title="Günlük kayıt silinsin mi?" description="İştah, enerji, kilo ve belirti bilgileri kalıcı olarak geçmişten kaldırılacak." onDelete={remove}/></div></div>}</DialogContent></Dialog>}

function DeleteConfirm({title,description,onDelete}:{title:string;description:string;onDelete:()=>void}){return <AlertDialog><AlertDialogTrigger asChild><Button variant="outline" className="danger-wide"><Trash2/>Kaydı sil</Button></AlertDialogTrigger><AlertDialogContent className="delete-dialog"><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction className="danger-confirm" onClick={onDelete}>Kaydı sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
function DetailSection({title,rows}:{title:string;rows:string[][]}){return <section className="detail-section"><h2>{title}</h2><div>{rows.map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div></section>}
function FilterSheet({open,close,value,setValue}:{open:boolean;close:()=>void;value:string;setValue:(s:string)=>void}){return <Dialog open={open} onOpenChange={o=>!o&&close()}><DialogContent showCloseButton={false} className="sheet-dialog"><div className="sheet-handle"/><button className="sheet-close" aria-label="Kapat" onClick={close}><X/></button><DialogTitle>Geçmişi filtrele</DialogTitle><Label>Kayıt türü</Label><div className="filter-chips">{["Tümü","Doz","Günlük","Kilo","Belirtiler"].map(x=><button key={x} className={value===x?"active":""} onClick={()=>setValue(x)}>{x}</button>)}</div><Button className="primary wide" onClick={close}>Uygula</Button></DialogContent></Dialog>}
const genders=["Kadın","Erkek","Diğer","Belirtmek istemiyorum"];
function validBirthDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||value>dateKey()||value<"1900-01-01")return false;const d=new Date(value+"T12:00:00");return !isNaN(d.getTime())&&dateKey(d)===value}
function validDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+"T12:00:00");return !isNaN(d.getTime())&&dateKey(d)===value}
function ProfileFields({name,gender,birthDate,setName,setGender,setBirthDate}:{name:string;gender:string;birthDate:string;setName:(v:string)=>void;setGender:(v:string)=>void;setBirthDate:(v:string)=>void}){return <><Field label="İsim"><Input autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} className="control"/></Field><Field label="Cinsiyet"><Select value={gender} onValueChange={setGender}><SelectTrigger className="control"><SelectValue placeholder="Seç"/></SelectTrigger><SelectContent>{genders.map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></Field><Field label="Doğum tarihi"><Input type="date" autoComplete="bday" min="1900-01-01" max={dateKey()} value={birthDate} onInput={e=>setBirthDate((e.target as HTMLInputElement).value)} className="control"/></Field>{birthDate&&!validBirthDate(birthDate)&&<p className="form-error" role="alert">Geçerli bir doğum tarihi seç.</p>}</>}
function DosePicker({med,dose,amount,onChange,existing}:{med:string;dose:string;amount:string;onChange:(d:string,a:string)=>void;existing?:Period}){
 const options=doseOptions[med]??[];
 const legacy=existing?.medication===med&&existing.dose&&!options.some(o=>o.dose===existing.dose&&o.amount===existing.amount)?{dose:existing.dose,amount:existing.amount}:null;
 const choices=legacy?[...options,legacy]:options;
 const value=choices.find(o=>o.dose===dose&&o.amount===amount);
 return <Field label="Kullanılan doz"><Select value={value?doseOptionKey(value):""} onValueChange={key=>{const option=choices.find(o=>doseOptionKey(o)===key);if(option)onChange(option.dose,option.amount)}}><SelectTrigger className="control"><SelectValue placeholder="Doz seç"/></SelectTrigger><SelectContent>{choices.map(o=><SelectItem key={doseOptionKey(o)} value={doseOptionKey(o)}>{doseOptionLabel(o)}{o===legacy?" · Mevcut kayıt":""}</SelectItem>)}</SelectContent></Select><small className="muted">Kendi ürünündeki değeri seç.</small></Field>
}
function SettingsDialog({open,close,data,setData}:{open:boolean;close:()=>void;data:Store;setData:React.Dispatch<React.SetStateAction<Store>>}){
 return <Dialog open={open} onOpenChange={o=>!o&&close()}><DialogContent className="settings-dialog profile-dialog" showCloseButton={false}>{open&&<SettingsDialogBody close={close} data={data} setData={setData}/>}</DialogContent></Dialog>
}
function SettingsDialogBody({close,data,setData}:{close:()=>void;data:Store;setData:React.Dispatch<React.SetStateAction<Store>>}){
 const [editing,setEditing]=useState(false),[name,setName]=useState(data.profile.name),[gender,setGender]=useState(data.profile.gender??""),[birthDate,setBirthDate]=useState(data.profile.birthDate??"");
 const save=()=>{if(!name.trim()||(birthDate&&!validBirthDate(birthDate)))return;setData(d=>({...d,profile:{...d.profile,name:name.trim(),gender,birthDate}}));setEditing(false)};
 return <><button className="sheet-close" aria-label="Profili kapat" onClick={close}><X/></button><DialogHeader><DialogTitle>Profilim</DialogTitle><DialogDescription>Bilgilerini buradan görüntüleyip düzenleyebilirsin.</DialogDescription></DialogHeader>{editing?<><ProfileFields name={name} gender={gender} birthDate={birthDate} setName={setName} setGender={setGender} setBirthDate={setBirthDate}/><div className="daily-actions"><Button variant="outline" onClick={()=>setEditing(false)}>Vazgeç</Button><Button className="primary" disabled={!name.trim()||!!birthDate&&!validBirthDate(birthDate)} onClick={save}>Kaydet</Button></div></>:<><div className="profile-summary"><span className="profile-avatar"><UserRound/></span><h2>{data.profile.name}</h2></div><DetailSection title="Kişisel bilgiler" rows={[["İsim",data.profile.name],["Cinsiyet",data.profile.gender||"Henüz eklenmedi"],["Doğum tarihi",data.profile.birthDate&&validBirthDate(data.profile.birthDate)?pretty(data.profile.birthDate):"Henüz eklenmedi"]]}/><Button className="primary wide" onClick={()=>{setName(data.profile.name);setGender(data.profile.gender??"");setBirthDate(data.profile.birthDate??"");setEditing(true)}}><Pencil/>Profili düzenle</Button></>}</>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
